import { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Advanced Garage System',
    name_en: 'Advanced Garage System',
    name_ja: '高度なガレージシステム',
    name_zh: '高级车库系统',
    name_zh_tw: '高級車庫系統',
    name_ko: '고급 차고 시스템',
    name_es: 'Sistema de Garaje Avanzado',
    name_fr: 'Système de Garage Avancé',
    name_de: 'Erweitertes Garagen-System',
    description: 'Complete vehicle garage system with customization and storage features.',
    description_en: 'Complete vehicle garage system with customization and storage features.',
    description_ja: 'カスタマイズとストレージ機能を備えた完全な車両ガレージシステム。',
    description_zh: '具有自定义和存储功能的完整车辆车库系统。',
    description_zh_tw: '具有自訂義和存儲功能的完整車輛車庫系統。',
    description_ko: '맞춤화 및 저장소 기능이 있는 완벽한 차량 차고 시스템입니다.',
    description_es: 'Sistema completo de garaje de vehículos con características de personalización y almacenamiento.',
    description_fr: 'Système de garage de véhicules complet avec fonctionnalités de personnalisation et de stockage.',
    description_de: 'Vollständiges Fahrzeuggarage-System mit Anpassungs- und Speicherfunktionen.',
    price: 4999,
    category: 'esx',
    image_url: 'https://via.placeholder.com/400x300?text=Garage+System',
    version: '2.1.0',
    framework: 'ESX',
    features: [
      'Multi-garage support',
      'Vehicle customization',
      'Owner system',
      'Database integration',
    ],
    requirements: [
      'ESX Framework',
      'Mysql-async',
      'Server resources',
    ],
    is_free: false,
    is_featured: true,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-03-20T10:00:00Z',
    download_count: 1250,
  },
  {
    id: '2',
    name: 'Drug System',
    name_en: 'Drug System',
    name_ja: 'ドラッグシステム',
    name_zh: '毒品系统',
    name_zh_tw: '毒品系統',
    name_ko: '약물 시스템',
    name_es: 'Sistema de Drogas',
    name_fr: 'Système de Drogue',
    name_de: 'Drogensystem',
    description: 'Fully featured drug dealing and production system with NPC interactions.',
    description_en: 'Fully featured drug dealing and production system with NPC interactions.',
    description_ja: 'NPC相互作用を備えた完全に機能した麻薬取引・生産システム。',
    description_zh: '具有NPC交互功能的功能齐全的毒品交易和生产系统。',
    description_zh_tw: '具有NPC交互功能的功能齐全的毒品交易和生產系統。',
    description_ko: 'NPC 상호작용을 포함한 완전한 기능의 마약 거래 및 생산 시스템입니다.',
    description_es: 'Sistema completo de tráfico y producción de drogas con interacciones de NPC.',
    description_fr: 'Système complet de trafic et de production de drogue avec interactions PNJ.',
    description_de: 'Vollständiges Drogenhändler- und Produktionssystem mit NPC-Interaktionen.',
    price: 5999,
    category: 'esx',
    image_url: 'https://via.placeholder.com/400x300?text=Drug+System',
    version: '1.8.5',
    framework: 'ESX',
    features: [
      'Production system',
      'Selling locations',
      'Money laundering',
      'Police alert system',
      'Player-to-player trading',
    ],
    requirements: [
      'ESX Framework',
      'Mysql-async',
      'Target System',
    ],
    is_free: false,
    is_featured: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-03-18T10:00:00Z',
    download_count: 2100,
  },
  {
    id: '3',
    name: 'Banking System',
    name_en: 'Banking System',
    name_ja: '銀行システム',
    name_zh: '银行系统',
    name_zh_tw: '銀行系統',
    name_ko: '은행 시스템',
    name_es: 'Sistema Bancario',
    name_fr: 'Système Bancaire',
    name_de: 'Banksystem',
    description: 'Advanced banking system with ATMs, loans, and account management.',
    description_en: 'Advanced banking system with ATMs, loans, and account management.',
    description_ja: 'ATM、ローン、アカウント管理を備えた高度な銀行システム。',
    description_zh: '具有ATM、贷款和账户管理的高级银行系统。',
    description_zh_tw: '具有ATM、貸款和帳戶管理的高級銀行系統。',
    description_ko: 'ATM, 대출 및 계좌 관리가 포함된 고급 은행 시스템입니다.',
    description_es: 'Sistema bancario avanzado con cajeros automáticos, préstamos y gestión de cuentas.',
    description_fr: 'Système bancaire avancé avec distributeurs automatiques, prêts et gestion de comptes.',
    description_de: 'Erweitertes Banksystem mit Geldautomaten, Darlehen und Kontoverwaltung.',
    price: 3999,
    category: 'qbcore',
    image_url: 'https://via.placeholder.com/400x300?text=Banking+System',
    version: '3.2.1',
    framework: 'QBCore',
    features: [
      'Multiple bank accounts',
      'ATM network',
      'Loan system',
      'Bank robberies',
      'Interest system',
    ],
    requirements: [
      'QBCore Framework',
      'Mysql-async',
      'QB-target',
    ],
    is_free: false,
    is_featured: true,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-03-22T10:00:00Z',
    download_count: 1875,
  },
  {
    id: '4',
    name: 'Job System Framework',
    name_en: 'Job System Framework',
    name_ja: 'ジョブシステムフレームワーク',
    name_zh: '工作系统框架',
    name_zh_tw: '工作系統框架',
    name_ko: '직업 시스템 프레임워크',
    name_es: 'Marco del Sistema de Trabajo',
    name_fr: 'Cadre du Système de Travail',
    name_de: 'Job-System-Framework',
    description: 'Flexible job creation framework for easy custom job implementation.',
    description_en: 'Flexible job creation framework for easy custom job implementation.',
    description_ja: 'カスタムジョブの簡単な実装のための柔軟なジョブ作成フレームワーク。',
    description_zh: '用于轻松实现自定义工作的灵活工作创建框架。',
    description_zh_tw: '用於輕鬆實現自訂義工作的靈活工作建立框架。',
    description_ko: '사용자 지정 작업을 쉽게 구현할 수 있는 유연한 작업 생성 프레임워크입니다.',
    description_es: 'Marco de creación de trabajos flexible para una fácil implementación de trabajo personalizado.',
    description_fr: 'Cadre flexible de création de travail pour une mise en œuvre facile des travaux personnalisés.',
    description_de: 'Flexibles Job-Erstellungs-Framework für einfache benutzerdefinierte Job-Implementierung.',
    price: 2999,
    category: 'standalone',
    image_url: 'https://via.placeholder.com/400x300?text=Job+System',
    version: '2.0.0',
    framework: 'Standalone',
    features: [
      'Job creation API',
      'Task system',
      'Reward system',
      'Cooldown management',
      'Easy configuration',
    ],
    requirements: [
      'No framework required',
      'MySQL database',
    ],
    is_free: false,
    is_featured: false,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-03-19T10:00:00Z',
    download_count: 950,
  },
  {
    id: '5',
    name: 'Free Chat System',
    name_en: 'Free Chat System',
    name_ja: '無料チャットシステム',
    name_zh: '免费聊天系统',
    name_zh_tw: '免費聊天系統',
    name_ko: '무료 채팅 시스템',
    name_es: 'Sistema de Chat Gratuito',
    name_fr: 'Système de Chat Gratuit',
    name_de: 'Kostenloses Chat-System',
    description: 'Lightweight chat system with range-based messaging and emotes.',
    description_en: 'Lightweight chat system with range-based messaging and emotes.',
    description_ja: '範囲ベースのメッセージングとエモートを備えた軽量チャットシステム。',
    description_zh: '具有基于范围的消息传递和表情符号的轻量级聊天系统。',
    description_zh_tw: '具有基於範圍的消息傳遞和表情符號的輕量級聊天系統。',
    description_ko: '범위 기반 메시징 및 감정 표현이 있는 경량 채팅 시스템입니다.',
    description_es: 'Sistema de chat ligero con mensajería basada en rango y emotes.',
    description_fr: 'Système de chat léger avec messagerie basée sur la portée et emotes.',
    description_de: 'Leichtes Chat-System mit bereichsbasiertem Messaging und Emotes.',
    price: 0,
    category: 'free',
    image_url: 'https://via.placeholder.com/400x300?text=Chat+System',
    version: '1.5.2',
    framework: 'Both',
    features: [
      'Range-based messaging',
      'Emote system',
      'Admin commands',
      'Chat logging',
      'Multiple channels',
    ],
    requirements: [
      'FiveM client',
    ],
    is_free: true,
    is_featured: false,
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-03-21T10:00:00Z',
    download_count: 3200,
  },
  {
    id: '6',
    name: 'Property System Pro',
    name_en: 'Property System Pro',
    name_ja: 'プロパティシステムプロ',
    name_zh: '财产系统专业版',
    name_zh_tw: '財產系統專業版',
    name_ko: '부동산 시스템 프로',
    name_es: 'Sistema de Propiedades Pro',
    name_fr: 'Système de Propriétés Pro',
    name_de: 'Grundstückssystem Pro',
    description: 'Complete property ownership system with rentals and customization options.',
    description_en: 'Complete property ownership system with rentals and customization options.',
    description_ja: 'レンタルとカスタマイズオプション付きの完全な物件所有システム。',
    description_zh: '具有租赁和自定义选项的完整物业所有权系统。',
    description_zh_tw: '具有租賃和自訂義選項的完整物業所有權系統。',
    description_ko: '임대료 및 사용자 지정 옵션이 포함된 완벽한 자산 소유 시스템입니다.',
    description_es: 'Sistema completo de propiedad con opciones de alquiler y personalización.',
    description_fr: 'Système complet de propriété avec options de location et de personnalisation.',
    description_de: 'Vollständiges Grundstückseigentumssystem mit Miet- und Anpassungsoptionen.',
    price: 6999,
    category: 'premium',
    image_url: 'https://via.placeholder.com/400x300?text=Property+System',
    version: '2.5.0',
    framework: 'Both',
    features: [
      'Buy/sell properties',
      'Rental system',
      'Interior customization',
      'Safe system',
      'Tenant management',
      'Property taxes',
    ],
    requirements: [
      'Framework choice',
      'MySQL database',
    ],
    is_free: false,
    is_featured: true,
    created_at: '2024-01-25T10:00:00Z',
    updated_at: '2024-03-20T10:00:00Z',
    download_count: 1620,
  },
  {
    id: '7',
    name: 'Police System',
    name_en: 'Police System',
    name_ja: '警察システム',
    name_zh: '警察系统',
    name_zh_tw: '警察系統',
    name_ko: '경찰 시스템',
    name_es: 'Sistema Policial',
    name_fr: 'Système Policier',
    name_de: 'Polizeisystem',
    description: 'Comprehensive police dispatch system with wanted levels and jail mechanics.',
    description_en: 'Comprehensive police dispatch system with wanted levels and jail mechanics.',
    description_ja: '指名手配レベルと刑務所メカニクスを備えた包括的な警察配置システム。',
    description_zh: '具有通缉级别和监狱机制的综合警察派遣系统。',
    description_zh_tw: '具有通緝級別和監獄機制的綜合警察派遣系統。',
    description_ko: '지명수배 수준 및 감옥 메커니즘이 있는 포괄적인 경찰 파견 시스템입니다.',
    description_es: 'Sistema completo de despacho policial con niveles de búsqueda y mecánicas de cárcel.',
    description_fr: 'Système complet de dispatch policier avec niveaux de recherche et mécaniques de prison.',
    description_de: 'Umfassendes Polizeieinsatzsystem mit Fahndungsstufen und Gefängnismechaniken.',
    price: 5499,
    category: 'qbcore',
    image_url: 'https://via.placeholder.com/400x300?text=Police+System',
    version: '3.1.0',
    framework: 'QBCore',
    features: [
      'Dispatch system',
      'Jail system',
      'Wanted system',
      'Evidence storage',
      'Police inventory',
      'Call system',
    ],
    requirements: [
      'QBCore Framework',
      'QB-target',
      'QB-dispatch',
    ],
    is_free: false,
    is_featured: false,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-03-17T10:00:00Z',
    download_count: 1450,
  },
  {
    id: '8',
    name: 'Housing Framework',
    name_en: 'Housing Framework',
    name_ja: 'ハウジングフレームワーク',
    name_zh: '住房框架',
    name_zh_tw: '住房框架',
    name_ko: '주택 프레임워크',
    name_es: 'Marco de Vivienda',
    name_fr: 'Cadre de Logement',
    name_de: 'Wohnungsrahmen',
    description: 'Complete housing system with interiors, storage, and multiple features.',
    description_en: 'Complete housing system with interiors, storage, and multiple features.',
    description_ja: 'インテリア、ストレージ、複数の機能を備えた完全なハウジングシステム。',
    description_zh: '具有内部、存储和多个功能的完整住房系统。',
    description_zh_tw: '具有內部、存儲和多個功能的完整住房系統。',
    description_ko: '인테리어, 저장소 및 여러 기능이 있는 완벽한 주택 시스템입니다.',
    description_es: 'Sistema completo de vivienda con interiores, almacenamiento y múltiples funciones.',
    description_fr: 'Système de logement complet avec intérieurs, stockage et plusieurs fonctionnalités.',
    description_de: 'Vollständiges Wohnungssystem mit Innenräumen, Speicherung und mehreren Funktionen.',
    price: 7499,
    category: 'premium',
    image_url: 'https://via.placeholder.com/400x300?text=Housing+Framework',
    version: '2.8.3',
    framework: 'Both',
    features: [
      'Multiple house interiors',
      'Furniture system',
      'Safe system',
      'Guest management',
      'House permissions',
      'Rent system',
    ],
    requirements: [
      'Framework choice',
      'MySQL database',
      '3D menu system',
    ],
    is_free: false,
    is_featured: true,
    created_at: '2024-01-30T10:00:00Z',
    updated_at: '2024-03-23T10:00:00Z',
    download_count: 2350,
  },
];
